import {
  EditorConfigSet,
  EditorWidgetType,
  PropertyDataType,
} from '@/core/types';

export const componentsConfig: { [elementType: string]: EditorConfigSet } = {
  section: {
    name: {
      label: 'Nume Secțiune',
      dataType: PropertyDataType.String,
      widgetType: EditorWidgetType.TextInput,
      responsive: false,
    },
    'style.height': {
      label: 'Înălțime Secțiune (px)',
      dataType: PropertyDataType.Number,
      widgetType: EditorWidgetType.NumberInput,
      min: 0,
      step: 1,
      responsive: true,
    },
    'style.backgroundColor': {
      label: 'Culoare Fundal',
      dataType: PropertyDataType.Color,
      widgetType: EditorWidgetType.ColorPicker,
      responsive: false,
    },
    backgroundImage: {
      label: 'Imagine Fundal',
      dataType: PropertyDataType.Object,
      widgetType: EditorWidgetType.ImageUpload,
      responsive: false,
    },
  },
  text: {
    name: {
      label: 'Nume Element',
      dataType: PropertyDataType.String,
      widgetType: EditorWidgetType.TextInput,
      responsive: false,
    },
    content: {
      label: 'Introdu textul',
      dataType: PropertyDataType.String,
      widgetType: EditorWidgetType.TextArea,
      responsive: false,
    },
    'style.width': {
      label: 'Latime element (px)',
      dataType: PropertyDataType.Number,
      widgetType: EditorWidgetType.NumberInput,
      min: 0,
      step: 1,
      responsive: true,
    },
    'style.textAlign': {
      label: 'Aliniere text',
      dataType: PropertyDataType.String,
      widgetType: EditorWidgetType.TextAlignment,
      responsive: true,
    },
    'style.fontWeight': {
      label: 'Grosime text',
      dataType: PropertyDataType.String,
      widgetType: EditorWidgetType.FontWeight,
      responsive: true,
    },
    'style.fontSize': {
      label: 'Dimensiune text',
      dataType: PropertyDataType.Number,
      widgetType: EditorWidgetType.NumberInput,
      responsive: true,
      min: 1,
    },
    'style.color': {
      label: 'Culoare text',
      dataType: PropertyDataType.Color,
      widgetType: EditorWidgetType.ColorPicker,
      responsive: false,
    },
    position: {
      responsive: true,
      label: 'Poziție Element',
      dataType: PropertyDataType.Object,
      widgetType: EditorWidgetType.PositionInput,
      min: 0,
      max: 9999,
      step: 1,
    },
  },
  image: {
    name: {
      label: 'Nume Element',
      dataType: PropertyDataType.String,
      widgetType: EditorWidgetType.TextInput,
      responsive: false,
    },
    'style.height': {
      label: 'Înălțime Secțiune (px)',
      dataType: PropertyDataType.Number,
      widgetType: EditorWidgetType.NumberInput,
      min: 0,
      step: 1,
      responsive: true,
    },
    'style.width': {
      label: 'Latime Secțiune (px)',
      dataType: PropertyDataType.Number,
      widgetType: EditorWidgetType.NumberInput,
      min: 0,
      step: 1,
      responsive: true,
    },
    'style.borderRadius': {
      label: 'Rotunjire colturi (%)',
      dataType: PropertyDataType.Number,
      widgetType: EditorWidgetType.NumberInput,
      min: 0,
      max: 100,
      step: 1,
      responsive: true,
    },
    position: {
      responsive: true,
      label: 'Poziție Element (%)',
      dataType: PropertyDataType.Object,
      widgetType: EditorWidgetType.PositionInput,
      min: 0,
      max: 100,
      step: 1,
    },
    backgroundImage: {
      label: 'Imagine Fundal',
      dataType: PropertyDataType.Object,
      widgetType: EditorWidgetType.ImageUpload,
      responsive: false,
    },
  },
  blob: {
    name: {
      label: 'Nume Element',
      dataType: PropertyDataType.String,
      widgetType: EditorWidgetType.TextInput,
      responsive: false,
    },
    'style.width': {
      label: 'Latime Secțiune (%)',
      dataType: PropertyDataType.Number,
      widgetType: EditorWidgetType.NumberInput,
      min: 0,
      step: 1,
      max: 100,
      responsive: true,
    },
    'style.color': {
      label: 'Culoare text',
      dataType: PropertyDataType.Color,
      widgetType: EditorWidgetType.ColorPicker,
      responsive: false,
    },
    position: {
      responsive: true,
      label: 'Poziție Element (%)',
      dataType: PropertyDataType.Object,
      widgetType: EditorWidgetType.PositionInput,
      min: 0,
      max: 100,
      step: 1,
    },
    blobName: {
      responsive: false,
      label: 'Selectare model',
      dataType: PropertyDataType.String,
      widgetType: EditorWidgetType.BlobSelector,
    },
  },
  container: {
    name: {
      label: 'Nume Element',
      dataType: PropertyDataType.String,
      widgetType: EditorWidgetType.TextInput,
      responsive: false,
    },
    'style.width': {
      label: 'Latime Secțiune (%)',
      dataType: PropertyDataType.Number,
      widgetType: EditorWidgetType.NumberInput,
      min: 0,
      step: 1,
      max: 100,
      responsive: true,
    },
    'style.height': {
      label: 'Inaltime Secțiune (%)',
      dataType: PropertyDataType.Number,
      widgetType: EditorWidgetType.NumberInput,
      min: 0,
      step: 1,
      max: 100,
      responsive: true,
    },
    'style.borderRadius': {
      label: 'Rotunjire colturi (%)',
      dataType: PropertyDataType.Number,
      widgetType: EditorWidgetType.NumberInput,
      min: 0,
      max: 100,
      step: 1,
      responsive: true,
    },
    'style.backgroundColor': {
      label: 'Culoare text',
      dataType: PropertyDataType.Color,
      widgetType: EditorWidgetType.ColorPicker,
      responsive: false,
    },
    position: {
      responsive: true,
      label: 'Poziție Element (%)',
      dataType: PropertyDataType.Object,
      widgetType: EditorWidgetType.PositionInput,
      min: 0,
      max: 100,
      step: 1,
    },
    borderStyles: {
      responsive: true,
      label: 'Configurare margini',
      dataType: PropertyDataType.Object,
      widgetType: EditorWidgetType.BorderEditor,
    },
  },
};
