import {
  EditorConfigSet,
  EditorWidgetType,
  PropertyDataType,
} from '@/core/types';

export const componentsConfig: { [elementType: string]: EditorConfigSet } = {
  section: {
    name: {
      label: 'Nume Secțiune',
      dataType: PropertyDataType.String,
      widgetType: EditorWidgetType.TextInput,
      responsive: false,
    },
    'style.height': {
      label: 'Înălțime Secțiune (px)',
      dataType: PropertyDataType.Number,
      widgetType: EditorWidgetType.NumberInput,
      min: 0,
      step: 1,
      responsive: false,
    },
    'style.backgroundColor': {
      label: 'Culoare Fundal',
      dataType: PropertyDataType.Color,
      widgetType: EditorWidgetType.ColorPicker,
      responsive: false,
    },
    backgroundImage: {
      label: 'Imagine Fundal',
      dataType: PropertyDataType.Object,
      widgetType: EditorWidgetType.ImageUpload,
      responsive: false,
    },
  },
  text: {
    name: {
      label: 'Nume Element',
      dataType: PropertyDataType.String,
      widgetType: EditorWidgetType.TextInput,
      responsive: false,
    },
    content: {
      label: 'Introdu textul',
      dataType: PropertyDataType.String,
      widgetType: EditorWidgetType.TextInput,
      responsive: false,
    },
    'style.fontSize': {
      label: 'Dimensiune text',
      dataType: PropertyDataType.Number,
      widgetType: EditorWidgetType.NumberInput,
      responsive: true,
      min: 1,
    },
    'style.color': {
      label: 'Culoare text',
      dataType: PropertyDataType.Color,
      widgetType: EditorWidgetType.ColorPicker,
      responsive: false,
    },
    position: {
      responsive: true,
      label: 'Poziție Element',
      dataType: PropertyDataType.Object,
      widgetType: EditorWidgetType.PositionInput,
      min: 0,
      max: 100,
      step: 1,
    },
  },
  image: {
    name: {
      label: 'Nume Element',
      dataType: PropertyDataType.String,
      widgetType: EditorWidgetType.TextInput,
      responsive: false,
    },
    'style.height': {
      label: 'Înălțime Secțiune (px)',
      dataType: PropertyDataType.Number,
      widgetType: EditorWidgetType.NumberInput,
      min: 0,
      step: 1,
      responsive: true,
    },
    'style.width': {
      label: 'Latime Secțiune (px)',
      dataType: PropertyDataType.Number,
      widgetType: EditorWidgetType.NumberInput,
      min: 0,
      step: 1,
      responsive: true,
    },
    'style.borderRadius': {
      label: 'Rotunjire colturi (%)',
      dataType: PropertyDataType.Number,
      widgetType: EditorWidgetType.NumberInput,
      min: 0,
      max: 100,
      step: 1,
      responsive: true,
    },
    position: {
      responsive: true,
      label: 'Poziție Element (%)',
      dataType: PropertyDataType.Object,
      widgetType: EditorWidgetType.PositionInput,
      min: 0,
      max: 100,
      step: 1,
    },
    backgroundImage: {
      label: 'Imagine Fundal',
      dataType: PropertyDataType.Object,
      widgetType: EditorWidgetType.ImageUpload,
      responsive: false,
    },
  },
};
