import { PricingTier } from '@/core/types';

export const PLANYVITE_EVENT_PLANS: PricingTier[] = [
  {
    id: 'basic',
    type: 'basic',
    name: 'Basic',
    price: 'Gratuit',
    description: 'Testeaza functionalitatile gratuit',
    features: [
      '5 răspunsuri',
      'Valabilitate 48h',
      'Editare invitatie',
      'Plan locatie - Demo',
      'Checklist',
    ],
    cta: 'Cumpara',
    order: 1,
  },
  {
    id: 'premium',
    type: 'premium',
    name: 'Premium',
    price: 249,
    oldPrice: 350,
    description: 'Acces la functionalitatile de baza',
    features: [
      'Raspunsuri nelimitate',
      'Valabilitate 6 luni',
      'Editare invitatie',
      'Plan locatie - Demo',
      'Checklist',
    ],
    cta: 'Cumpara',
    order: 2,
    priceId: 'price_1RanVvIYmtfnTY0fzQ0a5e5p',
  },
  {
    id: 'ultimate',
    type: 'ultimate',
    name: 'Ultimate',
    price: 349,
    oldPrice: 450,
    description: 'Acces la toate functionalitatile platformei',
    features: [
      'Raspunsuri nelimitate',
      'Valabilitate 12 luni',
      'Editare invitatie',
      'Plan locatie',
      'Asezare la mese',
      'exportare invitati in excel',
      'Export plan locatie PDF',
      'Checklist',
      'Planificator eveniment avansat',
    ],
    cta: 'Cumpara',
    popular: true,
    order: 3,
    priceId: 'price_1RanWvIYmtfnTY0fY32J21QY',
  },
  {
    id: 'ultimate_upgrade',
    type: 'ultimate',
    name: 'Ultimate',
    price: 100,
    oldPrice: 450,
    description: 'Acces la toate functionalitatile platformei',
    features: [
      'Raspunsuri nelimitate',
      'Valabilitate 12 luni',
      'Editare invitatie',
      'Plan locatie',
      'Asezare la mese',
      'exportare invitati in excel',
      'Export plan locatie PDF',
      'Checklist',
      'Planificator eveniment avansat',
    ],
    cta: 'Cumpara',
    popular: true,
    order: 4,
    priceId: 'price_1RanY8IYmtfnTY0fvDG9pzfI',
  },
];

export const PLANYVITE_EVENT_PLAN_FEATURES = {
  basic: {
    maxGuests: 5,
    maxTablePlanElements: 2,
    nrOfGuestsAvailableInTablePlan: 5,
    allowGifs: false,
    allowCountdown: false,
    // ...other features
  },
  premium: {
    maxGuests: 99999,
    maxTablePlanElements: 2,
    nrOfGuestsAvailableInTablePlan: 5,
    allowGifs: true,
    allowCountdown: true,
    // ...other features
  },
  ultimate: {
    maxGuests: 99999,
    maxTablePlanElements: Infinity,
    nrOfGuestsAvailableInTablePlan: Infinity,
    allowGifs: true,
    allowCountdown: true,
    // ...other features
  },
};
